<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <RootNamespace>MicaFlyouts</RootNamespace>
    <AssemblyName>MicaFlyouts</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>Assets\MicaFlyouts.ico</ApplicationIcon>
    <Platforms>x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' And ('$(Platform)' == '' Or '$(Platform)' == 'AnyCPU' Or '$(Platform)' == 'Any CPU')">$(NETCoreSdkPortableRuntimeIdentifier)</RuntimeIdentifier>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <CsWin32RunAsBuildTask>true</CsWin32RunAsBuildTask>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <IsAotCompatible>true</IsAotCompatible>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CsWinRTAotOptimizerEnabled>true</CsWinRTAotOptimizerEnabled>
    <InvariantGlobalization>false</InvariantGlobalization>
    <LangVersion>preview</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!--  CS1591 Generate documents "Missing XML comment"  -->
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <WarningsAsErrors>$(WarningsAsErrors);CsWinRT1028;CsWinRT1030;IDE0301;IDE0305</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.UI.Reactor" />
    <PackageReference Include="H.NotifyIcon.WinUI" />
    <PackageReference Include="Microsoft.WindowsAppSDK.WinUI" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" />
    <PackageReference Include="Microsoft.Windows.CsWin32" />
    <PackageReference Include="NAudio" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Infrastructure\Interop\NativeMethods.txt" />
    <AdditionalFiles Include="Strings\**\*.resw" />
    <EmbeddedResource Include="Assets\MicaFlyouts.ico" LogicalName="MicaFlyouts.Assets.MicaFlyouts.ico" />
    <EmbeddedResource Include="Assets\TrayIcons\*.ico" />
    <Content Include="Assets\MicaFlyouts.ico" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\**\*" Exclude="Assets\MicaFlyouts.ico" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Strings\**\*.resw" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
