<Project>
  <Target Name="_CopyWinUIResourcesForAot"
          AfterTargets="Publish"
          Condition="'$(PublishAot)' == 'true' and '$(WindowsPackageType)' == 'None'">
    <ItemGroup>
      <_WinUIResourcesForAot Include="$(TargetDir)Reactor\**\*.xbf" />
    </ItemGroup>
    <Copy SourceFiles="@(_WinUIResourcesForAot)"
          DestinationFiles="@(_WinUIResourcesForAot->'$(PublishDir)%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true"
          Condition="'@(_WinUIResourcesForAot)' != ''" />
    <Copy SourceFiles="$(TargetDir)$(AssemblyName).pri"
          DestinationFiles="$(PublishDir)$(AssemblyName).pri"
          SkipUnchangedFiles="true"
          Condition="Exists('$(TargetDir)$(AssemblyName).pri')" />
  </Target>
</Project>
