<Project>
  <Target Name="_CopyWinUIResourcesForAot"
          AfterTargets="Publish"
          Condition="'$(PublishAot)' == 'true' and '$(WindowsPackageType)' == 'None'">
    <ItemGroup>
      <_WinUIResourcesForAot Include="$(OutputPath)**\*.xbf" />
      <_WinUIResourcesForAot Include="$(OutputPath)$(AssemblyName).pri"
                             Condition="Exists('$(OutputPath)$(AssemblyName).pri')" />
    </ItemGroup>
    <Copy SourceFiles="@(_WinUIResourcesForAot)"
          DestinationFiles="@(_WinUIResourcesForAot->'$(PublishDir)%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true"
          Condition="'@(_WinUIResourcesForAot)' != ''" />
  </Target>
</Project>
